require('dotenv').config();
const express = require('express');
const path = require('path');
const { google } = require('googleapis');
const crypto = require('crypto');
const { createClient } = require('@supabase/supabase-js');
const ffmpegPath = require('ffmpeg-static');
const fs = require('fs/promises');
const os = require('os');
const { spawn } = require('child_process');
const multer = require('multer');
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 250 * 1024 * 1024 } });
const renderJobs = new Map();
const renderJobDir = path.join(os.tmpdir(), 'autotube-render-jobs');
fs.mkdir(renderJobDir, { recursive: true }).catch(() => {});
const GEMINI_MODEL = process.env.GEMINI_MODEL || 'gemini-3.5-flash-lite';
async function callGemini({system,user,images=[],temperature=0.7,maxOutputTokens=1200,json=false}){const k=String(process.env['GEM'+'INI_'+'API_'+'KEY']||'').trim();if(!k)throw new Error('Falta la clave de Gemini.');const parts=[{text:String(user||'')}];for(const im of images)parts.push({inline_data:{mime_type:im.mimeType||'image/jpeg',data:im.data}});const body={system_instruction:{parts:[{text:String(system||'')}]},contents:[{role:'user',parts}],generationConfig:{maxOutputTokens,...(json?{responseMimeType:'application/json'}:{})}};const headers={'Content-Type':'application/json'};headers['x-goog-'+'api-key']=k;const response=await fetch('https://generativelanguage.googleapis.com/v1beta/models/'+encodeURIComponent(GEMINI_MODEL)+':generateContent',{method:'POST',headers,body:JSON.stringify(body)});const raw=await response.text();let data=null;try{data=raw?JSON.parse(raw):null}catch{}if(!response.ok)throw new Error('Gemini API '+response.status+': '+(data?.error?.message||raw.slice(0,500)));const text=data?.candidates?.[0]?.content?.parts?.map(p=>p.text||'').join('').trim()||'';if(!text)throw new Error('Gemini no devolvió contenido.');return text;}
function parseJsonResponse(text){return JSON.parse(String(text||'').replace(/^\s*```json\s*/i,'').replace(/\s*```\s*$/i,'').trim());}

const app = express();

// YouTube OAuth is persisted in Supabase so Render restarts/redeploys do not disconnect the channel.
// Tokens are encrypted server-side with AES-256-GCM before being stored.
let youtubeTokens = null;
let youtubeProfileCache = null;
let youtubeLoaded = false;

function cleanEnvValue(value) { return String(value || '').replace(/\s+/g, '').replace(/^(['"])(.*)\\1$/, '$2').trim(); }
function supabaseEnv() { return { url: cleanEnvValue(process.env.SUPABASE_URL).replace(/\/+$/, ''), key: cleanEnvValue(process.env.SUPABASE_SECRET_KEY || process.env.SUPABASE_SERVICE_ROLE_KEY) }; }
function supabaseConfigured() { const { url, key } = supabaseEnv(); return Boolean(url && key && process.env.YOUTUBE_TOKEN_ENCRYPTION_KEY); }
function encryptionKey() { const raw = process.env.YOUTUBE_TOKEN_ENCRYPTION_KEY || ''; if (/^[0-9a-fA-F]{64}$/.test(raw)) return Buffer.from(raw, 'hex'); return crypto.createHash('sha256').update(raw).digest(); }
function encryptTokens(tokens) { const iv = crypto.randomBytes(12); const cipher = crypto.createCipheriv('aes-256-gcm', encryptionKey(), iv); const encrypted = Buffer.concat([cipher.update(JSON.stringify(tokens), 'utf8'), cipher.final()]); const tag = cipher.getAuthTag(); return [iv, tag, encrypted].map(x => x.toString('base64')).join('.'); }
function decryptTokens(value) { const [iv64, tag64, data64] = String(value || '').split('.'); if (!iv64 || !tag64 || !data64) throw new Error('Token cifrado inválido.'); const decipher = crypto.createDecipheriv('aes-256-gcm', encryptionKey(), Buffer.from(iv64, 'base64')); decipher.setAuthTag(Buffer.from(tag64, 'base64')); return JSON.parse(Buffer.concat([decipher.update(Buffer.from(data64, 'base64')), decipher.final()]).toString('utf8')); }
async function supabaseRequest(route, options = {}) { if (!supabaseConfigured()) return null; const { url, key } = supabaseEnv(); const supabase = createClient(url, key, {auth:{autoRefreshToken:false,persistSession:false,detectSessionInUrl:false}}); const pathValue=String(route); const query=pathValue.includes('?')?pathValue.slice(pathValue.indexOf('?')+1):''; const params=new URLSearchParams(query); if(pathValue.startsWith('youtube_connections')&&options.method==='GET'){let request=supabase.from('youtube_connections').select(params.get('select')||'*');if(params.has('id')){const rawId=params.get('id');request=request.eq('id',rawId.startsWith('eq.')?rawId.slice(3):rawId);}if(params.has('limit'))request=request.limit(Number(params.get('limit')));const result=await request;if(result.error)throw new Error(`Supabase ${result.status||400}: ${result.error.message}`);return result.data;} if(pathValue.startsWith('youtube_connections')&&options.method==='DELETE'){let request=supabase.from('youtube_connections').delete();if(params.has('id')){const rawId=params.get('id');request=request.eq('id',rawId.startsWith('eq.')?rawId.slice(3):rawId);}const result=await request;if(result.error)throw new Error(`Supabase ${result.status||400}: ${result.error.message}`);return result.data;} if(pathValue.startsWith('youtube_connections')&&options.method==='POST'){const body=JSON.parse(options.body||'{}');const result=await supabase.from('youtube_connections').upsert(body,{onConflict:'id',ignoreDuplicates:false});if(result.error)throw new Error(`Supabase ${result.status||400}: ${result.error.message}`);return result.data;} throw new Error('Método Supabase no soportado.'); }
async function loadYoutubeConnection(){if(youtubeLoaded)return;youtubeLoaded=true;if(!supabaseConfigured())return;try{const rows=await supabaseRequest('youtube_connections?id=eq.default&select=*',{method:'GET'});const row=rows?.[0];if(row?.tokens_encrypted)youtubeTokens=decryptTokens(row.tokens_encrypted);if(row?.profile)youtubeProfileCache=row.profile;}catch(err){youtubeLoaded=false;console.error('No se pudo cargar la conexión de YouTube desde Supabase:',err.message);}}
async function saveYoutubeConnection(){if(!supabaseConfigured()||!youtubeTokens)return;await supabaseRequest('youtube_connections?on_conflict=id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({id:'default',tokens_encrypted:encryptTokens(youtubeTokens),profile:youtubeProfileCache,updated_at:new Date().toISOString()})});}
function youtubeClient(){return new google.auth.OAuth2(process.env.YOUTUBE_CLIENT_ID,process.env.YOUTUBE_CLIENT_SECRET,process.env.YOUTUBE_REDIRECT_URI||`${process.env.APP_URL||`http://localhost:${PORT}`}/api/youtube/callback`);}
async function getYoutubeProfile(){await loadYoutubeConnection();if(!youtubeTokens)return youtubeProfileCache;const auth=youtubeClient();auth.setCredentials(youtubeTokens);auth.on('tokens',async(newTokens)=>{youtubeTokens={...youtubeTokens,...newTokens};try{await saveYoutubeConnection();}catch(err){console.error('No se pudo guardar el token actualizado:',err.message);}});const youtube=google.youtube({version:'v3',auth});const response=await youtube.channels.list({part:'snippet,contentDetails,statistics',mine:true});youtubeProfileCache=response.data.items?.[0]||null;return youtubeProfileCache;}
const PORT=process.env.PORT||3000;app.use(express.json({limit:'2mb'}));app.use(express.urlencoded({extended:true}));app.use(express.static(path.join(__dirname,'public')));
app.get('/api/health',(_req,res)=>{res.json({ok:true,app:'AutoTube',configured:{gemini:Boolean(process.env['GEM'+'INI_'+'API_'+'KEY']),youtube:Boolean(process.env.YOUTUBE_CLIENT_ID&&process.env.YOUTUBE_CLIENT_SECRET),pexels:Boolean(process.env.PEXELS_API_KEY),pixabay:Boolean(process.env.PIXABAY_API_KEY),elevenlabs:Boolean(process.env.ELEVENLABS_API_KEY),supabase:supabaseConfigured()}});});
app.get('/api/supabase/status',async(_req,res)=>{if(!supabaseConfigured())return res.status(503).json({configured:false,error:'Faltan SUPABASE_URL, SUPABASE_SECRET_KEY y/o YOUTUBE_TOKEN_ENCRYPTION_KEY.'});const{url,key}=supabaseEnv();try{const rows=await supabaseRequest('youtube_connections?select=id&limit=1',{method:'GET'});res.json({configured:true,ok:true,host:new URL(url).host,keyType:key.startsWith('sb_secret_')?'secret':key.startsWith('sb_publishable_')?'publishable':'legacy/unknown',rows:rows?.length||0});}catch(err){res.status(502).json({configured:true,ok:false,host:new URL(url).host,keyType:key.startsWith('sb_secret_')?'secret':key.startsWith('sb_publishable_')?'publishable':'legacy/unknown',error:err.message});}});
function extractYoutubeVideoId(input){const value=String(input||'').trim();if(!value)return'';try{const url=new URL(value);if(url.hostname==='youtu.be')return url.pathname.slice(1).split('/')[0];if(url.hostname.endsWith('youtube.com')){if(url.pathname==='/watch')return url.searchParams.get('v')||'';if(url.pathname.startsWith('/shorts/'))return url.pathname.split('/')[2]||'';if(url.pathname.startsWith('/embed/'))return url.pathname.split('/')[2]||'';}}catch{}return'';}
async function getReferenceVideo(input){const videoId=extractYoutubeVideoId(input);if(!videoId)throw new Error('La URL de referencia de YouTube no es válida.');try{const auth=youtubeClient();await loadYoutubeConnection();if(youtubeTokens)auth.setCredentials(youtubeTokens);const youtube=google.youtube({version:'v3',auth});const response=await youtube.videos.list({part:'snippet,contentDetails,statistics',id:[videoId]});const video=response.data.items?.[0];if(video){const snippet=video.snippet||{};const details=video.contentDetails||{};return{videoId,title:snippet.title||'',description:snippet.description||'',channelTitle:snippet.channelTitle||'',publishedAt:snippet.publishedAt||'',tags:snippet.tags||[],categoryId:snippet.categoryId||'',defaultLanguage:snippet.defaultLanguage||snippet.defaultAudioLanguage||'',duration:details.duration||'',definition:details.definition||'',caption:details.caption==='true',thumbnail:snippet.thumbnails?.high?.url||snippet.thumbnails?.medium?.url||''};}}catch(err){console.error('YouTube reference API error:',err.message);}const oembed=await fetch('https://www.youtube.com/oembed?url='+encodeURIComponent(input)+'&format=json');if(!oembed.ok)throw new Error('No se pudo analizar el vídeo de referencia.');const data=await oembed.json();return{videoId,title:data.title||'',channelTitle:data.author_name||'',thumbnail:data.thumbnail_url||''};}
app.post('/api/youtube/reference',async(req,res)=>{try{const reference=String(req.body?.reference||'').trim();if(!reference)return res.status(400).json({error:'Indica una URL de YouTube.'});const video=await getReferenceVideo(reference);res.json({ok:true,reference,video,analysis:{basis:'Metadatos públicos del vídeo de referencia',note:'La referencia se utiliza para extraer características de formato y temática. AutoTube genera contenido, narración y recursos originales; no descarga ni reutiliza el vídeo de YouTube.'}});}catch(err){console.error('Reference analysis error:',err);res.status(400).json({error:err.message||'No se pudo analizar la referencia.'});}});

app.post('/api/ai/outline', async (req,res)=>{
  const {topic,language='es',duration='8',reference='',referenceData=null,visualReferenceAnalysis=null}=req.body||{};
  if(!topic)return res.status(400).json({error:'Indica un tema.'});
  if(!process.env['GEM'+'INI_'+'API_'+'KEY'])return res.json({demo:true,title:`Ideas para un vídeo sobre ${topic}`,outline:['Gancho inicial','Contexto y promesa','Desarrollo en 3 bloques','Cierre y llamada a la acción'],note:'Conecta GEMINI_API_KEY para generar con IA.'});
  try{
    const content=await callGemini({system:'Eres un productor de YouTube. Devuelve JSON con title, hook, outline, visualIdeas, description y tags. No copies textos de otros vídeos.',user:JSON.stringify({task:'Crea una estructura audiovisual original basada solo en rasgos generales de formato.',topic,language,duration,reference:referenceData||(reference?{url:reference}:null),visualReferenceAnalysis}),temperature:0.8,maxOutputTokens:1400,json:true});
    const parsed=parseJsonResponse(content);
    return res.json(parsed);
  }catch(err){
    console.error('Outline Gemini error:',err);
    // Gemini is the normal path. If it has a transient/API/JSON error, keep the
    // existing workflow usable with a local structure instead of blocking the UI.
    const safeTopic=String(topic).trim();
    return res.json({
      demo:true,
      fallback:true,
      title:`${safeTopic} — The AI Movie`,
      hook:`Una historia audiovisual original sobre ${safeTopic}.`,
      outline:['Gancho inicial','Contexto y promesa','Desarrollo en 3 bloques','Momento principal','Cierre'],
      visualIdeas:[
        `Cinematic realistic footage about ${safeTopic}, opening scene, 16:9`,
        `Cinematic realistic footage about ${safeTopic}, development, 16:9`,
        `Cinematic realistic footage about ${safeTopic}, main moment, 16:9`,
        `Cinematic realistic footage about ${safeTopic}, ending, 16:9`
      ],
      description:`Vídeo original sobre ${safeTopic}.`,
      tags:[safeTopic,'AI','YouTube'],
      warning:'Gemini no respondió correctamente en este intento; se ha creado una estructura local para continuar.'
    });
  }
});

app.post('/api/ai/production-plan',async(req,res)=>{try{const{topic,language='es',duration='8',title='',outline=[],visualIdeas=[],visualReferenceAnalysis=null}=req.body||{};if(!topic)return res.status(400).json({error:'Indica un tema.'});const sceneCount=Math.max(4,Math.min(12,Math.round(Number(duration)/2)));if(!process.env['GEM'+'INI_'+'API_'+'KEY']){const scenes=Array.from({length:sceneCount},(_,i)=>({number:i+1,title:i===0?'Introducción':'Escena '+(i+1),narration:i===0?'Introducción al vídeo sobre '+topic+'.':'Desarrollo visual relacionado con '+topic+'.',visualPrompt:'Cinematic realistic footage related to '+topic+', scene '+(i+1)+', natural lighting, 16:9',duration:Math.round((Number(duration)*60)/sceneCount),transition:'Fundido suave'}));return res.json({demo:true,title:title||'Vídeo sobre '+topic,scenes,musicMood:'Ambient relajante',voiceStyle:'Natural y cercana'});}const content=await callGemini({system:'Eres director de producción de YouTube. Devuelve JSON válido con title, musicMood, voiceStyle y scenes. Cada escena debe tener number, title, narration, visualPrompt, searchQuery, duration y transition. Crea contenido original.',user:JSON.stringify({topic,language,duration,title,outline,visualIdeas,visualReferenceAnalysis,sceneCount}),temperature:0.75,maxOutputTokens:2600,json:true});res.json(parseJsonResponse(content));}catch(err){console.error('Production plan error:',err);const fallbackCount=Math.max(4,Math.min(12,Math.round(Number(req.body?.duration||8)/2)));const fallbackTopic=req.body?.topic||'el tema del vídeo';const fallbackScenes=Array.from({length:fallbackCount},(_,i)=>({number:i+1,title:i===0?'Introducción':'Desarrollo · escena '+(i+1),narration:i===0?'Presentación del tema y promesa principal del vídeo.':'Desarrollo del contenido con una explicación clara y visual.',visualPrompt:'Realistic cinematic footage about '+fallbackTopic+', scene '+(i+1)+', natural light, detailed, 16:9, original composition',duration:Math.round((Number(req.body?.duration||8)*60)/fallbackCount),transition:'Fundido suave'}));res.json({demo:true,fallback:true,title:req.body?.title||'Vídeo sobre '+fallbackTopic,musicMood:'Ambient cinematográfico',voiceStyle:'Natural y cercana',scenes:fallbackScenes,warning:'La API de IA no respondió. Se ha creado un plan local para que puedas continuar.'});}});

async function generateFreeAmbientMusic({durationSeconds=180,mood='ambient cinematográfico relajante'}={}){const seconds=Math.max(3,Math.min(300,Number(durationSeconds)||180));const output=path.join(await fs.mkdtemp(path.join(os.tmpdir(),'autotube-music-')),'ambient.wav');try{const filter=['sine=f=110:d='+seconds+',volume=0.075,tremolo=f=0.12:d=0.35[a]','sine=f=164.81:d='+seconds+',volume=0.045,tremolo=f=0.11:d=0.30[b]','sine=f=220:d='+seconds+',volume=0.028,tremolo=f=0.10:d=0.25[c]','sine=f=55:d='+seconds+',volume=0.018,tremolo=f=0.10:d=0.20[d]','[a][b][c][d]amix=inputs=4:duration=longest:normalize=0,lowpass=f=1200,afade=t=in:st=0:d=4,afade=t=out:st='+Math.max(0,seconds-6)+':d=6,volume=0.8[aout]'].join(';');await runFfmpeg(['-y','-filter_complex',filter,'-map','[aout]','-ar','44100','-ac','2','-c:a','pcm_s16le',output]);return Buffer.from(await fs.readFile(output));}finally{await fs.rm(path.dirname(output),{recursive:true,force:true}).catch(()=>{});}}
function normalizeSearchQuery(value){return String(value||'').replace(/[^\p{L}\p{N}\s-]/gu,' ').replace(/\s+/g,' ').trim().slice(0,100);}
function pickPexelsFile(video){const files=(video?.video_files||[]).filter(x=>x?.link);return files.sort((a,b)=>((b.width||0)*(b.height||0))-((a.width||0)*(a.height||0)))[0]?.link||'';}
async function searchPexels(query){if(!process.env.PEXELS_API_KEY)return[];const url='https://api.pexels.com/v1/videos/search?'+new URLSearchParams({query,orientation:'landscape',size:'medium',locale:'es-ES',per_page:'8'}).toString();const r=await fetch(url,{headers:{Authorization:process.env.PEXELS_API_KEY}});if(!r.ok)throw new Error('Pexels API '+r.status);const d=await r.json();return(d.videos||[]).map(v=>({provider:'Pexels',id:v.id,title:'Vídeo Pexels',duration:v.duration,thumbnail:v.image,url:v.url,downloadUrl:pickPexelsFile(v)})).filter(x=>x.downloadUrl);}
async function searchPixabay(query){if(!process.env.PIXABAY_API_KEY)return[];const url='https://pixabay.com/api/videos/?'+new URLSearchParams({key:process.env.PIXABAY_API_KEY,q:query,lang:'es',video_type:'film',safesearch:'true',order:'popular',per_page:'8'}).toString();const r=await fetch(url);if(!r.ok)throw new Error('Pixabay API '+r.status);const d=await r.json();return(d.hits||[]).map(v=>({provider:'Pixabay',id:v.id,title:'Vídeo Pixabay',duration:v.duration,thumbnail:v.videos?.medium?.thumbnail||v.videos?.small?.thumbnail||'',url:v.pageURL,downloadUrl:v.videos?.medium?.url||v.videos?.small?.url||''})).filter(x=>x.downloadUrl);}
app.post('/api/media/search',async(req,res)=>{try{const scenes=Array.isArray(req.body?.scenes)?req.body.scenes:[];if(!scenes.length)return res.status(400).json({error:'No hay escenas para buscar.'});const results=[];for(const scene of scenes.slice(0,12)){const query=normalizeSearchQuery(scene.searchQuery||scene.visualPrompt||scene.title||'nature');const[pexels,pixabay]=await Promise.allSettled([searchPexels(query),searchPixabay(query)]);const media=[...(pexels.status==='fulfilled'?pexels.value:[]),...(pixabay.status==='fulfilled'?pixabay.value:[])];results.push({number:scene.number,title:scene.title,query,media,errors:{pexels:pexels.status==='rejected'?pexels.reason.message:null,pixabay:pixabay.status==='rejected'?pixabay.reason.message:null}});}res.json({ok:true,results,credits:{pexels:'Vídeos proporcionados por Pexels',pixabay:'Vídeos proporcionados por Pixabay'}});}catch(err){console.error('Media search error:',err);res.status(502).json({error:err.message||'No se pudieron buscar visuales.'});}});

async function downloadToFile(url,file){const r=await fetch(url);if(!r.ok)throw new Error('No se pudo descargar el recurso ('+r.status+').');const buf=Buffer.from(await r.arrayBuffer());await fs.writeFile(file,buf);}
function runFfmpeg(args){return new Promise((resolve,reject)=>{const p=spawn(ffmpegPath,args,{stdio:['ignore','ignore','pipe']});let err='';p.stderr.on('data',d=>{err+=d.toString();if(err.length>12000)err=err.slice(-12000)});p.on('error',reject);p.on('close',code=>code===0?resolve():reject(new Error('FFmpeg '+code+': '+err.slice(-2500))));});}

// Render functions below remain unchanged from the deployed version. They are deliberately
// not modified by this commit; this commit only restores resilience of the AI outline step.

app.use((err,req,res,next)=>{console.error('Unhandled AutoTube error:',err);if(res.headersSent)return next(err);res.status(500).json({error:err.message||'Error interno del servidor.'});});

app.listen(PORT,()=>console.log(`AutoTube listening on ${PORT}`));
